### ISSUE TITLE
Create a flex-container class

### ISSUE THREAD

**Issue by mml1** [Wynforth33/tea_cozy#3]
It seems like you repeat 
```
display: flex;
flex-direction: column;
```

try creating a flex-container class with these stylings and use this class in addition to your other classes. You can have multiple classes which you can use by separating them with a space in like `div class ="item flex-container"`

**Comment by Wynforth33** [comment]
We had the same thought, i started consolidating into two clases; specifically for the next projects which require a 960px width 'containter' with margin: 0 auto; so i created two selectors in CSS one .flex{display:flex} and .container{width:960px; margin: 0 auto;}
